### ISSUE TITLE
Map - frontend map styling and base tiles

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/SA-UNHCR-Turkey#14]
The client is using a mapbox base layer which they have customized.

https://api.mapbox.com/styles/v1/lombie/cij8y506o001zbkkufq1t50hb.html?title=true&access_token=pk.eyJ1IjoibG9tYmllIiwiYSI6IlAyVlJfU3MifQ.gMTKJU_NsIvulLTttw4-XA#5.1/39.273/35.187 

The map should focus on Turkey on load, and should not include any additional geodata for provinces, as this data is integrated in the mapbox delivered tiles.

**Comment by PeaceGeeksProjects** [comment]
Verified on Turkey
