### ISSUE TITLE
Basic Deployment of Services Advisor Turkey environment

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/SA-UNHCR-Turkey#2]

**Comment by PeaceGeeksProjects** [comment]
User PeaceGeeksProjects added and verified here http://dev.admin.turkey.servicesadvisor.org/user

**Comment by PeaceGeeksProjects** [comment]
Need to add the 'Client' site and link to it from the landing page.  Now it links to Jordan's Client site

**Comment by PeaceGeeksProjects** [comment]
Verified http://dev.admin.turkey.servicesadvisor.org/node/1
