### ISSUE TITLE
Add a 'Type' field for the Service Provider

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/SA-UNHCR-Turkey#28]
Partner type: Government services;Municipal services;UN Agency;INGO;NGO; Civil Society (6 values)
Requested by Richard Shdeed
see also https://github.com/PeaceGeeksSociety/servicesadvisor-3.0/issues/52

**Comment by mackh** [comment]
I'm assuming this hold be for internal use only?
Is not displayed in the front end

**Comment by PeaceGeeksProjects** [comment]
I would agree for this release.  Reflecting it in the client App would be in the next system design phase (it may make sense).
